### ISSUE TITLE
ResourceExhaustedError: OOM

### ISSUE THREAD

**Issue by tengshan2008** [dongjun-Lee/text-classification-models-tf#4]
find a error when train the att_rnn model

Machine: 4 * Tesla P100-PCIE-16GB, memory: 256G

`
ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [563354,256] and type float
	 [[Node: embeddings/Adam/Initializer/zeros = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [563354,256] values: [0 0 0]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
`

**Comment by dongjun-Lee** [comment]
I guess another task was running on your GPU:0. Could you check it?

**Comment by tengshan2008** [comment]
Only my task running on GPU:0, and I set input shape in [64962, 128], but it is also OOM.

**Comment by tengshan2008** [comment]
Sorry. It is work, my workmate load data into memory but not start training, so I can't find job in ps list.

**Comment by sahil107** [comment]
<?xml version="1.0" encoding="utf-8"?> <feed xmlns="http://www.w3.org/2005/Atom"> <id>https://www.paypal-status.com</id> <title>PayPal Status - Event History</title> <updated>2018-09-04T19:26:39Z</updated> <generator>PayPal Status Feed Generator</generator> <author> <name>PayPal, Inc.</name> </author> <link rel="alternate" href="https://www.paypal-status.com"/> <subtitle>PayPal Incidents, bullens and scheduled maintenance</subtitle> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8422)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8422</id> <link href="https://www.paypal-status.com/history/eventdetails/8422"> </link> <updated>2018-09-04T18:48:29Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> Initial Notification: Maintenance Event Summary: Paydiant operations personnel will be performing the regularly scheduled bi-weekly connector release on 13-September-2018 from 9am ET – 12pm ET.<br /><br />Service(s) Affected: Connectors<br /><br />Region(s) Affected: All<br /><br />Action(s) Required: None.<br /><br />Expected Impact: None. There is no downtime planned or anticipated during this maintenance event window. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8422) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Sep 4, 18:48 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8421)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8421</id> <link href="https://www.paypal-status.com/history/eventdetails/8421"> </link> <updated>2018-09-04T18:40:08Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> Initial Notification: Maintenance Event Summary: Paydiant operations personnel will be performing the regularly scheduled monthly platform release on 12-September-2018 starting at 10:00pm ET.<br /><br />Service(s) Affected: Paydiant Production Services<br /><br />Region(s) Affected: All<br /><br />Action(s) Required: None<br /><br />Expected Impact: There will be up to a 10 minute delay in fuel site communications and sites may be temporarily disconnected during the maintenance window. The fuel sites should automatically reconnect using local retry logic.<br /><br />There is no impact to other services. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8421) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Sep 4, 18:40 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform – Sandbox Environment Maintenance (PP-CRI-8420)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8420</id> <link href="https://www.paypal-status.com/history/eventdetails/8420"> </link> <updated>2018-09-04T18:29:28Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> Maintenance Event Summary: Paydiant operations personnel will be performing the regularly scheduled monthly Sandbox platform release on 6-September-2018 starting at 09:00 AM ET.<br /><br />Service(s) Affected: Paydiant Services<br /><br />Region(s) Affected: All<br /><br />Action(s) Required: None<br /><br />Expected Impact: We will be upgrading the Paydiant Sandbox platform with multiple feature enhancements and bug fixes. The Paydiant Sandbox Environment will be unavailable during this time. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-CRI-8420) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Sep 4, 18:29 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Data Center maintenance - September 7 (PP-LIVE-8419)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8419</id> <link href="https://www.paypal-status.com/history/eventdetails/8419"> </link> <updated>2018-09-04T17:13:36Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> On September 7, 2018, PayPal will conduct planned maintenance on one of our data centers, which will require downtime of 1 continuous minute during the maintenance window.<br /><br />Customer experience impact:<br /><br /><ul><li>Partners and vendors can expect 100% impact to their connections to PayPal.</li><li>All internet traffic directed in and out of the impacted data center will be affected during the maintenance.</li><li>Any settlement jobs running during the maintenance window will be affected.</li><li>Connections to and from partners will time out.</li></ul><br />The maintenance window was selected to ensure minimal site impact.<br /><small>Sep 4, 17:13 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8417)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8417</id> <link href="https://www.paypal-status.com/history/eventdetails/8417"> </link> <updated>2018-09-04T16:07:13Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> Maintenance Event Summary: Paydiant operations personnel will be performing a planned maintenance on the production reporting portal server on 6-September-2018 starting at 05:00 PM ET.<br /><br />Service(s) Affected: Paydiant Partner Dashboards (https://reports.paydiant.com) <br /><br />Region(s) Affected: All<br /><br />Action(s) Required: None<br /><br />Expected Impact: Paydiant reporting portal will be unavailable during the time of the maintenance. <small>(edited) </small> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8417) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Sep 4, 16:07 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8409)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8409</id> <link href="https://www.paypal-status.com/history/eventdetails/8409"> </link> <updated>2018-08-31T19:46:11Z</updated> <content type="html"><![CDATA[<strong>Rescheduled: </strong> The scheduled maintenance has been rescheduled. We are sorry for any inconvenience. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8409) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 31, 19:46 UTC</small><br /><strong>Initial Notification: </strong> Maintenance Event Summary: Paydiant operations personnel will be performing platform maintenance on the Production environment to update SSL certificate configurations on 6-September-2018 starting at 09:00am ET.<br /><br />Service(s) Affected: Paydiant Production Environment<br /><br />Region(s) Affected: All<br /><br />Action(s) Required: None.<br /><br />Expected Impact: None. There is no downtime planned during this maintenance event window. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8409) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 27, 16:09 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[DigiCert Certificate Migration (PP-LIVE-8413)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8413</id> <link href="https://www.paypal-status.com/history/eventdetails/8413"> </link> <updated>2018-08-30T16:55:41Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> <div><span>PayPal is working towards migrating its SSL and TLS certificates to DigiCert as all major browser vendors, including <a href="https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html">Google</a>, <a href="https://support.apple.com/en-hk/HT208860">Apple</a> and <a href="https://blog.mozilla.org/security/2018/03/12/distrust-symantec-tls-certificates/">Firefox</a>, plan to distrust legacy certificates issued under the Symantec infrastructure.</span><span><br /></span></div><div><span><br /></span></div><div><span>During the time indicated, </span><span>we’ll perform a test on the following endpoints:</span></div><div><span><br /></span> </div><ul><li><span><a href="http://www.paypal.com">www.paypal.com</a></span><span></span></li><li><span><a href="http://www.paypalobjects.com">www.paypalobjects.com</a></span></li></ul><div><span>A merchant may experience the following issues based on their custom integration:</span><span><br /></span></div><div><ul><li><span>Fail to validate IPN</span></li><li><span>Fail to read the WSDL file from paypalobjects.com</span></li><li><span>General errors related to SSL certificate validation, such as <b>Unable to verify certificate</b></span></li></ul></div> <span>Merchants who experience these issues may need to update their certificates, see <a href="https://www.paypal-notice.com/en/Migration-to-DigiCert-Root-Certificates/">Migration to DigiCert Root Certificates</a> for additional information.</span><br /><small>Aug 30, 16:55 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[PayPal Maintenance - August 30 - PayPal live site (PP-LIVE-8410)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8410</id> <link href="https://www.paypal-status.com/history/eventdetails/8410"> </link> <updated>2018-08-29T19:50:16Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> <p><span>During the time indicated, there will be up to 1 minute </span><span>of impact <span>during which merchants may experience the following impact</span>:</span></p> <ul><li><span>Merchants and consumers may experience higher-than-normal transaction declines.</span></li><li><span>Merchants may encounter an increased number of <b>10001 - Internal Error</b> or <b>520002 -</b></span><b><span> </span></b><b><span>Internal Error</span></b><span> responses for API calls.</span></li><li><span>PayPal customers may also experience errors accessing the PayPal website (<a href="https://www.paypal.com">https://www.paypal.com</a>) or PayPal checkout flows.</span></li><li><span>PayPal REST APIs may result in HTTP 500 errors.</span><span></span></li><li><span>PayPal Here and Mobile In-Store payments may not complete.</span></li></ul><br /><small>Aug 29, 19:50 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8398)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8398</id> <link href="https://www.paypal-status.com/history/eventdetails/8398"> </link> <updated>2018-08-29T03:15:28Z</updated> <content type="html"><![CDATA[<strong>Completed: </strong> The scheduled maintenance has been completed. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8398) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 29, 03:15 UTC</small><br /><strong>Update 1: </strong> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8398) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 29, 02:04 UTC</small><br /><strong>Rescheduled: </strong> <span>The scheduled maintenance has been rescheduled. We are sorry for any inconvenience.</span> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8398) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 22, 21:45 UTC</small><br /><strong>Initial Notification: </strong> Maintenance Event Summary: Paydiant operations personnel will be performing routine maintenance on networking equipment on 22-August-2018, from 10:00pm ET - 11:59pm ET.<br /> <br />Service(s) Affected: All<br /> <br />Region(s) Affected: All<br /> <br />Action(s) Required: None.<br /> <br />Expected Impact: None. There is no downtime planned or anticipated during this maintenance event window.<br /> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8398) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 17, 15:45 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform – Certification Environment Maintenance (PP-CRI-8408)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8408</id> <link href="https://www.paypal-status.com/history/eventdetails/8408"> </link> <updated>2018-08-27T16:07:18Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> <p>Maintenance Event Summary: Paydiant operations personnel will be performing platform maintenance on the Certification environment to update SSL certificate configurations on 30-August-2018 starting at 09:00am ET.</p><p>Service(s) Affected: <span>Paydiant Certification Environment</span></p><p>Region(s) Affected: All</p><p>Action(s) Required: None.</p><p>Expected Impact: None. There is no downtime planned during this maintenance event window.</p> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-CRI-8408) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 27, 16:07 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Major Impact to Paydiant Platform (PP-LIVE-8407)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8407</id> <link href="https://www.paypal-status.com/history/eventdetails/8407"> </link> <updated>2018-08-26T14:57:15Z</updated> <content type="html"><![CDATA[<strong>Resolved: </strong> <span>This issue has been resolved as of Aug 26, 14:54 UTC.</span><div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8407) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 26, 14:57 UTC</small><br /><strong>Update 1: </strong> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8407) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 26, 14:10 UTC</small><br /><strong>Initial Notification: </strong> <p>We are experiencing a system issue which may be affecting Paydiant Platform on the Production environment.</p><p>Service(s) Affected: <span>Paydiant Fuel Services</span></p><p>Region(s) Affected: NA, AUS, UK</p><p>Action(s) Required: None.<span>Our Engineers are currently investigating</span></p><p>Expected Impact: <span>Some sites are unable to reconnect to Skybridge. </span></p> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8407) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 26, 13:13 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Issue with Express Checkout (PP-LIVE-8406)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8406</id> <link href="https://www.paypal-status.com/history/eventdetails/8406"> </link> <updated>2018-08-24T18:56:21Z</updated> <content type="html"><![CDATA[<strong>Resolved: </strong> This issue has been resolved as of Aug 24, 18:20 UTC.<br /><small>Aug 24, 18:56 UTC</small><br /><strong>Initial Notification: </strong> <span>We are experiencing a system issue which may be affecting Express Checkout on the Production environment.</span><span> Some Customers may not be correctly redirected from PayPal back to the Merchant web site while going through the online checkout experience. The root cause has been identified and our technical teams are working on the fix.</span><br /><small>Aug 24, 16:54 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8396)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8396</id> <link href="https://www.paypal-status.com/history/eventdetails/8396"> </link> <updated>2018-08-23T13:31:36Z</updated> <content type="html"><![CDATA[<strong>Completed: </strong> <span>The scheduled maintenance has been completed.</span> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8396) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 23, 13:31 UTC</small><br /><strong>Update 1: </strong> <span>The scheduled maintenance has started, please refer to information in Initial Notification below for details.</span> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8396) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 23, 12:59 UTC</small><br /><strong>Initial Notification: </strong> Paydiant operations personnel will be performing the regularly schedule bi-weekly connector release on 23-August-2018 from 9am ET – 12pm ET.<br /><p> </p><p> </p><p>Service(s) Affected: <span>Connectors.</span></p><p>Region(s) Affected: All</p><p>Action(s) Required: None.</p><p>Expected Impact: None. There is no downtime planned or anticipated during this maintenance event window.</p> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8396) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 17, 14:53 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8394)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8394</id> <link href="https://www.paypal-status.com/history/eventdetails/8394"> </link> <updated>2018-08-22T22:06:25Z</updated> <content type="html"><![CDATA[<strong>Update 2: </strong> <span>The scheduled maintenance has been completed.</span> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8394) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 22, 22:06 UTC</small><br /><strong>Update 1: </strong> <span>The scheduled maintenance has started, please refer to information in Initial Notification below for details.</span> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8394) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 22, 21:17 UTC</small><br /><strong>Initial Notification: </strong> <p>Maintenance Event Summary: Paydiant operations personnel will be performing a scheduled <span>maintenance for </span><span>Tableau reporting service</span> on 22-August-2018 starting at 05:00pm ET.</p><p>Service(s) Affected: <span>Paydiant Reporting Portal</span></p><p>Region(s) Affected: All</p><p>Action(s) Required: None.</p><p>Expected Impact: <span>The Paydiant </span><span>Tableau Production environment will be available during the maintenance window, however, you may notice stale reporting data during this timeframe. </span></p> <small>(edited) </small> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8394) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 15, 19:05 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[PayPal Sandbox Maintenance (PP-CRI-8405)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8405</id> <link href="https://www.paypal-status.com/history/eventdetails/8405"> </link> <updated>2018-08-22T17:32:59Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> The PayPal sandbox will undergo certificate updates during the specified times. The following endpoints will be unavailable during the maintenance. <div><span><br /></span></div><div><ul><li>www.sandbox.paypal.com</li><li>api.sandbox.paypal.com </li></ul></div><br /><small>Aug 22, 17:32 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Missing transactions from account history (PP-LIVE-8403)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8403</id> <link href="https://www.paypal-status.com/history/eventdetails/8403"> </link> <updated>2018-08-22T06:20:06Z</updated> <content type="html"><![CDATA[<strong>Resolved: </strong> This issue has been resolved as of Aug 22, 03:22 UTC.<br /><small>Aug 22, 06:20 UTC</small><br /><strong>Initial Notification: </strong> We are experiencing a system issue which may be preventing transactions from appearing in the merchant's account history. Our technical teams have been engaged and are actively troubleshooting the issue.<br /><small>Aug 21, 22:52 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Paydiant Platform Production Maintenance (PP-LIVE-8397)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8397</id> <link href="https://www.paypal-status.com/history/eventdetails/8397"> </link> <updated>2018-08-22T03:30:49Z</updated> <content type="html"><![CDATA[<strong>Completed: </strong> The scheduled maintenance has been completed. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8397) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 22, 03:30 UTC</small><br /><strong>Update 1: </strong> Maintenance has new updates <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8397) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 22, 01:55 UTC</small><br /><strong>Initial Notification: </strong> Maintenance Event Summary: Paydiant operations personnel will be performing routine maintenance on networking equipment on 21-August-2018, from 10:00pm ET - 11:59pm ET.<br /> <br />Service(s) Affected: All<br /> <br />Region(s) Affected: All<br /> <br />Action(s) Required: None.<br /> <br />Expected Impact: None. There is no downtime planned or anticipated during this maintenance event window.<br /> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8397) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 17, 15:44 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Major Impact to Paydiant Platform (PP-LIVE-8404)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8404</id> <link href="https://www.paypal-status.com/history/eventdetails/8404"> </link> <updated>2018-08-22T03:29:17Z</updated> <content type="html"><![CDATA[<strong>Resolved: </strong> This issue has been resolved as of Aug 22, 03:28 UTC. <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8404) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 22, 03:29 UTC</small><br /><strong>Initial Notification: </strong> <p>We are experiencing a system issue which may be affecting Paydiant Platform on the Production environment.</p><p>Service(s) Affected: <span>Paydiant Services</span></p><p>Action(s) Required: None. <span>Our Engineers are currently investigating.</span></p><p><span><br /></span></p> <br /> <br /> <br /> <div> You are receiving this notification because you have previously subscribed to receive notifications regarding the Retail Checkout components of PayPal, including the Paydiant Platform. You can manage your subscriptions using the links below. If you have any questions related to this notification, please contact your account manager or send an email to the Paydiant technical support team. Emails should include the notification number (PP-LIVE-8404) since it is a unique identifier for this communication. Thank you. <br /> </div><br /><small>Aug 22, 02:59 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[PayPal Maintenance (PP-LIVE-8401)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8401</id> <link href="https://www.paypal-status.com/history/eventdetails/8401"> </link> <updated>2018-08-21T13:56:09Z</updated> <content type="html"><![CDATA[<strong>Initial Notification: </strong> <div>During the time window indicated, there will be up to 1 minute during which merchants may experience the following impact.</div><div><span><br /></span></div><div><ul><li>Merchants and customers may experience higher-than-normal declines to transactions.</li><li>Merchants may encounter an increased number of "10001 - Internal Error" and/or "520002 -Internal Error" responses for API calls.</li><li>PayPal users may also experience errors accessing the PayPal website (https://www.paypal.com and/or the PayPal checkout flows.</li><li>PayPal REST APIs may result in HTTP 500 errors.</li><li>PayPal Here and Mobile In-Store payments may not complete.</li></ul></div><br /><small>Aug 21, 13:56 UTC</small><br />]]></content> </entry> <entry> <title type="html"><![CDATA[Impact to multiple Payflow products (PP-LIVE-8400)]]></title> <id>https://www.paypal-status.com/history/eventdetails/8400</id> <link href="https://www.paypal-status.com/history/eventdetails/8400"> </link> <updated>2018-08-21T04:36:47Z</updated> <content type="html"><![CDATA[<strong>Resolved: </strong> <div><span>We have experienced a system issue which affected multiple products on the Production environment. During the time of the incident Payflow merchants have been impacted with general errors (error code 99), internal errors (109), processor time out (104), processor unavailable (102), stream errors (103), host unavailable (106) errors, or Fraud Protection Services Filter - Not processed by filters (127) errors.</span></div><div><br /></div><div><span><div>Reference transactions and Captures run against transactions processed during the impacted time frame might currently fail. Technical teams are working on restoring the impacted transactions. </div><div><br /></div><div>Additionally, merchants might have encountered issues with accessing reports via https://manager.paypal.com. Merchant transactions attempted on Payflow Link and PayPal Manager Virtual Terminal may also have been impacted during the mentioned time frame.</div></span></div><div><span><br /></span></div><div><span>This issue has been resolved as of Aug 21, 02:08 UTC. </span></div> <small>(edited) </small><br /><small>Aug 21, 04:36 UTC</small><br />]]></content> </entry> </feed>

**Comment by dongjun-Lee** [comment]
@tengshan2008 No problem :)

**Comment by sahil107** [comment]
---------- Forwarded ----------
Sender: Sahil Shrivastav <sahil.shrivastava1989@gmail.com>
Date: Sep 29, 2018 19:10
Subject: com.creditmantri Crash Report
Recipient: 
CC: 

> USER_COMMENT=null
> ANDROID_VERSION=8.0.0
> APP_VERSION_NAME=2.3
> BRAND=samsung
> PHONE_MODEL=SM-A730F
> CUSTOM_DATA=
> STACK_TRACE=java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65637, result=-1, data=Intent { (has extras) }} to activity {com.creditmantri/com.cm.onboard.view.SignInActivity}: java.lang.RuntimeException: No compatible client available. Please change your scope
> at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
> at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
> at android.app.ActivityThread.-wrap20(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6944)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> Caused by: java.lang.RuntimeException: No compatible client available. Please change your scope
> at com.truecaller.android.sdk.TrueSDK.onActivityResultObtained(Unknown Source:35)
> at com.cm.onboard.view.SignInFragment.onActivityResult(SignInFragment.java:477)
> at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
> at android.app.Activity.dispatchActivityResult(Activity.java:7556)
> at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
> ... 9 more
> java.lang.RuntimeException: No compatible client available. Please change your scope
> at com.truecaller.android.sdk.TrueSDK.onActivityResultObtained(Unknown Source:35)
> at com.cm.onboard.view.SignInFragment.onActivityResult(SignInFragment.java:477)
> at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
> at android.app.Activity.dispatchActivityResult(Activity.java:7556)
> at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
> at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
> at android.app.ActivityThread.-wrap20(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6944)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
>
>
>
>
